### ISSUE TITLE
ccovey/ldap-auth v1.1.1 requires adldap/adldap 4.x-dev -> no matching package found.

### ISSUE THREAD

**Issue by nickdenardis** [ccovey/ldap-auth#16]
Trying to `composer update` on a fresh install of Laravel 4.1 yields this missing dependency.

Added in `composer.json`:

```
"require": {
    "laravel/framework": "4.1.*",
    "ccovey/ldap-auth": "1.1.x"
},
```

Then running a `composer update`:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ccovey/ldap-auth v1.1.1 requires adldap/adldap 4.x-dev -> no matching package found.
```

Weird because `adldap` is in Packagist: https://packagist.org/packages/adldap/adldap

But there doesn't seem to be a `-dev` tag on the github repo: https://github.com/ztec/adLDAP/tags

Anyone else having this issue?

**Comment by mogilny** [comment]
Yes. Facing the same problem. I think the solution would be to add 
<code>"adldap/adldap": "dev-master"</code>
instead of 
<code>"adLdap/adLdap": "4.x-dev"</code>

At least I was able to install the package "stand-alone"

**Comment by ccovey** [comment]
@nickdenardis @mogilny this should be fixed now, merged in @nickdenardis 's PR
