### ISSUE TITLE
Missing Folders

### ISSUE THREAD

**Issue by mogilny** [ccovey/ldap-auth#18]
Hi
Pls close this issue if I'm asking something stupid, as I'm not sure if this is an issue or if I'm doing something wrong.

Just wanted to install the latest version. Therefore I've added <code>"ccovey/ldap-auth": "dev-master",</code> to the laravel main composer.json file. Unfortunately, it wasn't successful. Which is strange, because #16 should already have solved that problem.
Received the follwoing error message:

``` php
Problem 1
    - Installation request for ccovey/ldap-auth dev-master -> satisfiable by ccovey/ldap-auth[dev-master].
    - ccovey/ldap-auth dev-master requires adldap/adldap dev-master -> no matching package found.
```

So I have donwloaded and installed both of the packeges manualy. <code>"ccovey/ldap-auth": "dev-master"</code> and <code>"adldap/adldap": "dev-master"</code>. This did work, expect one thing.
In the composer.json of this package there is an autoload section:

``` php
"autoload": {
        "classmap": [
            "src/migrations"
        ],
        "psr-0": {
            "Ccovey\\LdapAuth": "src/"
        }
    },
```

The stanard folders config / lang / <b>migrations</b> / views are missing in the current release. If I do add them manualy, everything is working as expected.

(Sorry for my bad English)

**Comment by ccovey** [comment]
Unfortunately right now all I got is composer is drunk...I'll dig in more when I get off work.

**Comment by ccovey** [comment]
this is fixed in latested tagged release, haven't merged into master or dev yet though. Will do so shortly.
