### ISSUE TITLE
DB role in authenticating a user?

### ISSUE THREAD

**Issue by from2day** [ccovey/ldap-auth#19]
Hi,

this is very use full library. I can connect to AD, retrieve users information. 
However I can't figure out what role and where the DB takes in this process?

I cannot authenticate user if there is one in my users table with the username I am trying to login e.g.

```
AD user
      'username' => 'somename'
      'displayname' => 'Some Name'
      'primarygroup' => 'Admins'
      'groups' => 
        array
          'IT' => 'IT'
          'Power Users' => 'Poer Users'
DB user
      'id' => 1 
      'username' => 'somename'
      'password_old' => 'i do not save passwords to DB '
Form fields
     'username' => 'somename'
     'password' => 'ad_password'
```

I assume that Auth is trying to authenticate to DB instead of AD. And I cannot follow the code to debug the steps of the library.

Thanks.

**Comment by ccovey** [comment]
The DB does nothing in the form of authentication. The only reason for it is so you can store additional info you may need in the database. The first thing to check is make sure you don't have anything inyour error logs. Next make sure you have set the username field in auth.php looks like you are using the default but set it to be sure.

**Comment by from2day** [comment]
Hm.. 
I've set:

``` php
..\app\config\auth.php
<?php
return array(
    'driver' => 'ldap',
        'model' => 'User',
    'table' => 'users',
    'reminder' => array(
        'email' => 'emails.auth.reminder',
        'table' => 'password_reminders',
        'expire' => 60,
    ),
    'username_field' => 'username',
);
```

When I try to connect with a user that is in both AD and DB. I am not logged in. Laravel.log. server logs are silent about this issue. Maybe you have more ideas?

**Comment by from2day** [comment]
My apologies. I am new to Laravel and I've left the User's model primary key unchanged. That caused problem: always redirecting to login screen.
I suggest you to mention that in config documentation, so that others like me would not appear.

``` php
class User extends Eloquent {
...
    protected $primaryKey = 'username';
...
```
