### ISSUE TITLE
With model usage, no tutorial or instruction

### ISSUE THREAD

**Issue by stevebauman** [ccovey/ldap-auth#23]
In your readme you say that this package can be used with a model:

"You can still use a model with this implementation as well if you want. ldap-auth will take your fields from ldap and attach them to the model allowing you to access things such as roles / permissions from the model if the account is valid in Active Directory."

But would you perhaps be able to give a tutorial or instruction how to attach your Auth driver to a model? I'm having trouble trying to figure it out, thanks!!

**Comment by ccovey** [comment]
Basically we just look at the model you declare in auth.php so by default it will use User. you can change that or have nothing at all. All the happens is we merge the ldap info returned with whatever is in the DB. The database has no influence on the authentication just allows you a plcae to store more info about the user.

I'll try and make that more clear.
