### ISSUE TITLE
User Model relationship

### ISSUE THREAD

**Issue by strebl** [ccovey/ldap-auth#26]
Great package so far, thanks!

But I have a problem. With the standard Auth Provider I can do something like tihs:

``` php
// app/models/User.php
public function exams()
{
    return $this->hasMany('Exam');
}
```

``` php
// app/routes.php
Route::get('/', function() {
    return Auth::user()->exams;
});
```

After I implemented your package I can't do that anymore:

```
ErrorException
Undefined index: exams
..vendor\ccovey\ldap-auth\src\Ccovey\LdapAuth\LdapUser.php
```

Am I doing something wrong or is that just not supported from your side?

**Comment by ccovey** [comment]
This is something I sort of knew about but didn't think of the implications with regards to relationships. I'll get something up here very soon that will fix the issue.

**Comment by strebl** [comment]
I have some weird problems..

I added the account_suffix to the username in the users table. Thats why couldn't use my relationships. After removing the suffix from the table, I can use Auth::relationship. But now the login fails silently...

If I change the Primarykey of the table from id to username booth works. But to be honest, that isn't what I want...

If I dd( Auth::check() ) while login, it says true. After the redirect it is false again...

Any advices?

**Comment by strebl** [comment]
After changing fields `username` to `userprincipalname` all is working as intended.

I can now use `Auth::posts()`
I can login without user in table
I can login with user in table

Maybe an example in the docs would be good?

**Comment by davidlanier** [comment]
Perhaps this is unrelated, but I am getting similar errors when trying to access the user's properties as defined at http://adldap.sourceforge.net/wiki/doku.php?id=documentation_user_functions#infocollection_username_fields_null 

I get an undefined index error on line 48 in vendor\ccovey\ldap-auth\src\Ccovey\LdapAuth\LdapUser.php when I try to use `Auth::user()->firstname` or any of the other properties listed on the sourceforge site.

```
* Dynamically access the user's attributes.
     *
     * @param  string  $key
     * @return mixed
     */
    public function __get($key)
    {
        return $this->attributes[$key];
    }
```

Also, while I'm here, is it possible to access the AD methods such as `Auth::user()->delete($username)` or ``` Auth::user()->groups($username, $recursive = NULL) ''' ?

**Comment by saleemepoch** [comment]
I am encountering the same issue. While logged in via LDAP, any creation or deletion of User throws this error:

ErrorException
Undefined index: id
open: D:\xampp\htdocs\laravel\vendor\ccovey\ldap-auth\src\Ccovey\LdapAuth\LdapUser.php
     \* Dynamically access the user's attributes.
     *
     \* @param  string  $key
     \* @return mixed
     */
    public function __get($key)
    {
        return $this->attributes[$key];
    }

Any help will be greatly appreciated. The package otherwise is very helpful. Thanks

**Comment by ccovey** [comment]
This is just for authentication, currently. I don't have plans currently to implement user crud but its not a terrible idea for another package in the future.
