### ISSUE TITLE
adLDAP exceptions

### ISSUE THREAD

**Issue by mbroughton** [ccovey/ldap-auth#3]
I've got an issue with my default route. Basically I'm checking Auth to see if a user is logged in or if they are a guest.

Route::get('/', 'LoginController@showLogin')->before('guest');

If the LDAP server is available, everything is peachy...however if it is down, I get adLDAP\adLDAPException "Bind to Active Directory failed. Check the login credentials and/or server details. AD said: Can't contact LDAP server", apparently before I ever get to my Login Controller (which has it's own error handling)

What's the best way to catch these errors?

**Comment by ccovey** [comment]
You will need to set up an error handler. 
`App::error(function(adLDAP\adLDAPException)
{
    // handle error everytime this excveption is thrown
});
`

You can put this code directly is something like app/start/global.php or somewhere else that makes more sense for your application.
