### ISSUE TITLE
Prevent running this when using Artisan and SSL/TLS enabled

### ISSUE THREAD

**Issue by syphernl** [ccovey/ldap-auth#31]
I cannot run (all) artisan commands with this module enabled. It results in an ErrorException regarding ldap_start_tls () because that only works when accessed via https/web.

Would it be possible to prevent loading/running this module when artisan is being used? It should be possible with `App::runningInConsole()` AFAIK.

**Comment by ccovey** [comment]
hmmm thats weird I have no issues running commands with this enabled. I'll dig in a bit more later tonight but If I don't find anything quickly I'll just use runningInConsole and be done with it. Thanks!

**Comment by syphernl** [comment]
But do you also use SSL or TLS in your settings? Without it, it does work fine until you enable SSL/TLS (which I've done because I also use AdLdap for other things besides this module)

**Comment by ccovey** [comment]
can't recreate this,  what command were you trying to use? I was able to manage queues, create controllers, publish views. all with tls enabled or ssl enabled. The service is deferred so it should only be instantiated when it is used.
