### ISSUE TITLE
Bypassing User Model for auth

### ISSUE THREAD

**Issue by jasonspick** [ccovey/ldap-auth#36]
I am using Sentry to manage permissions and it is my last stage in a multi stage auth. LDAP being my first. 

What I needed to accomplish was to always check the AD groups and make sure they matched. I could not do this because if the user existed locally in the db, it would not return the ldap groups to compare.

I found I could bypass the returning of the user model on auth if i did not include the model in app/config/auth.php and then I could always check Active directory and compare groups.

It might be helpful to include this information in your documentation.

thanks,

**Comment by ccovey** [comment]
You should always get back groups as long as you specify no fields or you do specify groups in your specified fields in the auth.php config. It wouldn't however return both. There is a section on models but I don't really say how to not use it only that it is optional. I'll make an update.

**Comment by jasonspick** [comment]
Thanks Cody!
