### ISSUE TITLE
AD data merging incorrectly into a local user.

### ISSUE THREAD

**Issue by trq** [ccovey/ldap-auth#9]
Just a reminder about our conversation on irc. It appears this line: https://github.com/ccovey/ldap-auth/blob/master/src/Ccovey/LdapAuth/LdapAuthUserProvider.php#L155 merges the local model with the AD data with the local data taking priority. I (we) believe this is the wrong way around.

**Comment by ccovey** [comment]
@trq this is fixed in master, when I get the other issues figured out i'll cut a new tag to be used.
